[project]
name = "wechat-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "itchat>=1.3.10",
    "jinja2>=3.1.6",
]
